#!/usr/bin/python3
import sys

''' Function to factorize a number into pairs of factors and print to stdout'''
def factorizeAndPrint(number):
    for i in range(2, number // 2 + 1):
        if number % i == 0:
            print(f"{number}={number // i}*{i}")
            break

def main(input_file):
    try:
        with open(input_file, 'r') as infile:
            for line in infile:
                number = int(line.strip())

                ''' Factorize the number and print each factorization to stdout'''
                factorizeAndPrint(number)
    except FileNotFoundError:
        print("Input file not found.")
    except Exception as e:
        print(f"An error occurred: {str(e)}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python factors.py <input_file>")
    else:
        input_file = sys.argv[1]
        main(input_file)
