#!/usr/bin/python3
import sys

def prime_factors(number):
    factors = []
    divisor = 2

    while number > 1:
        while number % divisor == 0:
            factors.append(divisor)
            number //= divisor
        divisor += 1

    return factors
def main(input_file):
    try:
        with open(input_file, 'r') as infile:
            for line in infile:
                number = int(line.strip())
                factors = prime_factors(number)
                if len(factors) == 2:
                    p, q = factors
                    print("{}={}*{}".format(number, p, q))
                else:
                    print("{} is not a product of exactly two prime numbers.".format(number))
    except FileNotFoundError:
        print("Input file not found.")
    except Exception as e:
        print("An error occurred: {}".format(str(e)))

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python factors <input_file>")
    else:
        input_file = sys.argv[1]
        main(input_file)
